config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :companies, only: [:new, :edit, :update, :create]
  resources :positions do
    resources :applicants, only: [:index]
  end
  resources :applicants, only: [:index, :new, :create]
  devise_for :users
  root 'home#index'
  get "/vaga/:slug", action: :public_position, controller: :positions, as: :public_position
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/applicant.rb
# frozen_string_literal: true

require 'csv'

class Applicant < ApplicationRecord
  belongs_to :user
  belongs_to :position
  validates :name, :email, :phone, :resume, presence: true
  has_one_attached :resume

  validate :correct_resume_mine_type

  def self.as_csv
   attributes = %w[id name email phone]

   CSV.generate(headers: true) do |csv|
    csv << attributes

    self.all.each do |applicant|
      csv << attributes.map { |attr| applicant.send(attr) }
    end
   end
  end
  


  private

  def correct_resume_mine_type
    if resume.attached? && !resume.content_type.in?('application/pdf')
      errors.add(:resume, 'foi enviado com um o tipo de documento inválido. Favor enviar somente PDF.')
    end
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brazil.rb
class Brazil
  class << self
    def states
      {
        'AC': 'Acre',
        'AL': 'Alagoas',
        'AP': 'Amapá',
        'AM': 'Amazonas',
        'BA': 'Bahia',
        'CE': 'Ceará',
        'DF': 'Distrito Federal',
        'ES': 'Espírito Santo',
        'GO': 'Goiás',
        'MA': 'Maranhão',
        'MT': 'Mato Grosso',
        'MS': 'Mato Grosso do Sul',
        'MG': 'Minas Gerais',
        'PA': 'Pará',
        'PB': 'Paraíba',
        'PR': 'Paraná',
        'PE': 'Pernambuco',
        'PI': 'Piauí',
        'RJ': 'Rio de Janeiro',
        'RN': 'Rio Grande do Norte',
        'RS': 'Rio Grande do Sul',
        'RO': 'Rondônia',
        'RR': 'Roraima',
        'SC': 'Santa Catarina',
        'SP': 'São Paulo',
        'SE': 'Sergipe',
        'TO': 'Tocantins'
      }
    end
  end
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user
  has_many :positions
  has_one_attached :logo
  validates :name, :url, :logo, presence: true
end

app/models/position.rb
class Position < ApplicationRecord
  belongs_to :company
  has_many :applicants

  enum career: [:developer, :business_inteligence, :information_tecnology, :desing,
                :product, :tecnology, :other]
  enum contract:[:clt, :pj, :match]
  has_rich_text :description
  validates :name, :career, :contract, :city, :state, :summary, presence: true

  before_save :set_slug

  private

  def set_slug
    # binding.pry
    self.slug = "#{self.company.name.parameterize}-#{self.name.parameterize}"
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_one :company
  has_many :applicants

  after_create :welcome_mail


  private

  def welcome_mail
    UserMailer.welcome(self).deliver_now
  end
  
end

app/controllers/applicants_controller.rb
# frozen_string_literal: true

class ApplicantsController < ApplicationController

  before_action :set_position, only: [:index]

  def index
    @applicants = @position.applicants
    respond_to do |format|
      format.html
      format.csv { send_data @position.applicants.as_csv }
      format.zip do
        UserMailer.export_resume(current_user, @position).deliver_now
        flash[:success] = 'Currículos gerados com sucesso!'
        redirect_to action: :index
      end
    end
  end

  def new; end

  def create
    @applicant = current_user.applicants.new(applicant_params)
    @position = Position.find(applicant_params[:position_id])

    respond_to do |format|
      if @applicant.save
        flash[:success] = 'Você acabou de aplicar para a vaga com sucesso!'
        format.html { redirect_to public_position_path(@applicant.position.slug) }
        format.js { render 'applicants/success' }
      else
        flash[:error] = 'Houve um erro ao aplicar para a vaga. Tente novamente.'
        format.html { render 'positions/public_position' }
        format.js { render partial: 'applicants/new' }
      end
    end
  end


  private

  def applicant_params
    @position = params.require(:applicant).permit(:name, :email, :phone, :position_id, :resume)
  end

  def set_position
    begin
      @position = current_user.company.positions.find(params[:position_id])
    rescue #ActiveRecord::RecordNotFound => e
      redirect_to positions_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def new
    @company = current_user.build_company
  end

  def edit
    @company = current_user.company
  end

  def create
    @company = current_user.build_company(company_params)
    if @company.save
      flash[:notice] = 'Empresa cadastrada com sucesso.'
      redirect_to root_path
    else
      flash[:notice] = 'Empresa cadastrada com sucesso.'
      render :new
    end
  end

  def update
    @company = current_user.company
    if @company.update(company_params)
      flash[:notice] = 'Empresa cadastrada com sucesso.'
      redirect_to root_path
    else
      render :edit
    end
    
  end

  private

  def company_params
    params.require(:company).permit(:name, :url, :logo)
  end
  
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @q = Position.ransack(params[:q])
    @positions = @q.result.page(params[:page]).per(params[:per])
    @contracts = [['CLT', 0], ['PJ', 1], ['A combinar', 2]]
  end
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_action :set_company, :set_i18n_careers, :set_i18n_contracts, except: [:public_position]
  before_action :set_position, only: [:edit, :show, :update]
  
  def index
    @positions = @company.positions
  end

  def new
    @position = @company.positions.new
  end

  def edit
  end

  def show
  end

  def create
    @position = @company.positions.new(params_position)
    if @position.save
      flash[:success] = 'Vaga cadastrada com sucesso.'
      redirect_to positions_path
    else
      render :new
    end
  end

  def update
    if @position.update(params_position)
      redirect_to positions_path
    else
      render :edit
    end
  end

  def public_position
    @position = Position.find_by(slug: params[:slug])
    @applicant = current_user.applicants.new(position_id: @position.id) if user_signed_in?

    respond_to do |format|
      format.html
      format.js { render partial: 'applicants/new' }
    end
  end



  private

  def set_position
    @position = @company.positions.find(params[:id])
  end

  def params_position
    params.require(:position).permit(:name, :career, :contract, :remote, :publish, :city, :state, :summary, :description)
  end

  def set_company
    redirect_to new_company_path if current_user.company.nil?
    @company = current_user.company
  end

  def set_i18n_careers
    @careers = I18n.t('activerecord.attributes.position.careers')
  end

  def set_i18n_contracts
    @contracts = I18n.t('activerecord.attributes.position.contracts')
  end
  
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
  def dynamic_url_company
    if current_user.company.present? && current_user.company.try(:id).present?
      edit_company_path(current_user.company)
    else
      new_company_path
    end
  end
end

app/helpers/positions_helper.rb
module PositionsHelper
  def text_position(position)
    "A empresa #{position.company.name} em #{position.city} está com a vaga de #{position.name}. Veja mais detalhes no nosso mural! #{url_position(position)}"
  end
  
  def url_position(position)
    public_position_url(position.slug)
  end

  def career_name(career)
    I18n.t('activerecord.attributes.position.careers')[career.to_sym]
  end

  def contract_name(contract)
    I18n.t('activerecord.attributes.position.contracts')[contract.to_sym]
  end
  
  def modality(position)
    position.remote ? 'Remoto' : 'Presencial'
  end
  
  
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/applicants/_form.html.haml
= simple_form_for @applicant, remote: (request.format.symbol == :js) ? true : false do |f|
  = f.hidden_field :position_id, value: @position.id
  = f.input :name
  = f.input :email, input_html: { value: current_user.email}
  = f.input :phone
  = f.input :resume, as: :file, hint: 'Aceitamos apenas arquivos PDF'
  = f.button :submit, 'Aplicar vaga', class: 'btn btn-primary'

app/views/applicants/_formmodal.html.haml
.modal-header
  %h5#modalLabel.modal-title= "Aplicar para a vaga: #{@position.name}"
  %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
    %span{"aria-hidden" => "true"} ×
.modal-body
  = render 'applicants/form'
.modal-footer
  %button.btn.btn-secondary{"data-dismiss" => "modal", :type => "button"} Fechar

app/views/applicants/_new.js.erb
$("#modal").find(".modal-content").html("<%= j render(:partial => 'applicants/formmodal', :locals => { :applicant => @applicant, :position => @position }) %>");
$("#modal").modal();

app/views/applicants/index.html.haml
%h2
  ="Candidaturas da vaga: #{@position.name}"
  = link_to 'Exportar CSV', position_applicants_path(@position, format: 'csv'), class: 'btn btn-primary btn-sm'
  = link_to 'Exportar Currículos', position_applicants_path(@position, format: 'zip'), class: 'btn btn-primary btn-sm'

%table.table
  %thead.thead-dark
    %tr
      %th{:scope => "col"} Nome
      %th{:scope => "col"} E-mail
      %th{:scope => "col"} Telefone
      %th{:scope => "col"} Currículo
  %tbody
    - @applicants.each do |applicant|
      %tr
        %th{:scope => "row"}= applicant.name
        %td= applicant.email
        %td= applicant.phone
        %td= link_to 'Download', rails_blob_path(applicant.resume, disposition: "attachment"), class: 'btn btn-warning btn-sm'

app/views/applicants/new.html.haml
%h1 Applicants#new
%p Find me in app/views/applicants/new.html.haml

app/views/applicants/success.js.erb
location.reload();

app/views/companies/_form.html.haml
= simple_form_for @company do |f| 
  = f.input :name 
  = f.input :url
  = image_tag(url_for(@company.logo), class: 'company-logo') unless @company.new_record? && !@company.logo.nil?
  = f.input :logo
  = f.button :submit, class: 'btn btn-primary'

app/views/companies/edit.html.haml
%h2 Minha Empresa
= render 'form'

app/views/companies/new.html.haml
%h2 Minha Empresa
= render 'form'

app/views/home/index.html.haml
%header.text-center
  %h1 Open Vagas
  %p Mural de vagas compartilhadas pela comunidade.

= search_form_for @q, url: root_path do |f|
  .row
    .col-sm
      .form-group
        = f.label :name_cont, "Carreira"
        = f.search_field :name_cont, class: 'form-control'

    .col-sm
      .form-group
        = f.label :contract_eq, "Modalidade"
        = f.select :contract_eq, options_from_collection_for_select(@contracts, :second, :first, @q.contract_eq), { include_blank: true }, { class: 'form-control' }

    .col-sm
      .form-group
        = f.label :state_eq, "Localidade"
        = f.select :state_eq, options_from_collection_for_select(Brazil.states, :first, :second, @q.contract_eq), {include_blank: true}, {class: 'form-control'}

    .col-sm
      %button.btn.btn-danger{type: 'submit', style: 'margin-top: 31px;'} Pesquisar

- @positions.each do |position|
  = render position

%p.d-block.text-center.mt-3
  .text-center= paginate @positions, theme: 'twitter-bootstrap-4'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title OpenVagas
    %meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'shared/topbar'
    %main.container{:role => "main"}
      = render partial: 'shared/flash_message'
      = yield
    %footer
      %p Desenvolvido por Fabrício
      %p= "Desde de #{Time.new.year}"

    #modal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "modalLabel", :tabindex => "-1"}
      .modal-dialog.modal-lg
        .modal-content
          

app/views/layouts/devise.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}/
    %title OpenVagas
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'devise', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    #logreg-forms
      = yield

app/views/positions/_form.html.haml
= simple_form_for @position do |f|
  = f.input :name
  = f.input :career, as: :select, collection: @careers, label_method: :second, value_method: :first, include_blank: false, selected: @position.career
  = f.input :contract, as: :select, collection: @contracts, label_method: :second, value_method: :first, include_blank: false, selected: @position.contract
  = f.input :remote
  = f.input :publish
  = f.input :city
  = f.input :state , as: :select, collection: Brazil.states, label_method: :second, value_method: :first
  = f.input :summary, maxlength: 360, input_html: { class: 'count-textarea', rows: 4 }
  #the-count
    %span#current 0
    %span#maximun / 360
  %label Descrição
  = f.rich_text_area :description
  = f.button :submit, class: 'btn btn-primary'

app/views/positions/_position.html.haml
.card.card-position
  .card-body
    .container.conteiner-card
      .row
        .col-2
          = image_tag position.company.logo, alt: "Logo marca da empresa #{position.company.name}", class: 'card-img-top'
        .col-10
          %h4= position.name
          %h5= "#{career_name(position.career)} - #{position.city} - #{contract_name(position.contract)}"
          %p Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam officia porro ab, nihil quis earum ratione repudiandae, ipsam neque quidem iusto commodi ipsum dolor cumque repellat fugiat corporis voluptatibus eaque.
          .row
            .col-sm.mt-3
              = link_to 'Ver mais', public_position_path(position.slug), class: 'btn btn-danger'
              - if user_signed_in?
                - if !UserApplicantQuery.new(current_user.id, position.id).call
                  
                  = link_to 'Candidatar-se', public_position_path(position.slug), {:remote => true, "data-target" => "#modal", "data-toggle" => "modal", 'data-backdrop' => 'static', 'data-keyboard' => 'false', class: 'btn btn-success'}
            .col-sm.text-right.mt-3.group-social-network
              = render partial: 'shared/social_network', locals: {position: position}

-# .card.card-position
-#   .card-body
-#     .container.conteiner-card
-#       .row
-#         .col-2
-#           = image_tag position.company.logo, alt: "Logo marca da empresa #{position.company.name}", class: 'card-img-top'
-#         .col-10
-#           %h4= position.name
-#           %h5= "#{career_name(position.career)} - #{position.city} - #{contract_name(position.contract)}"
-#           %p Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam officia porro ab, nihil quis earum ratione repudiandae, ipsam neque quidem iusto commodi ipsum dolor cumque repellat fugiat corporis voluptatibus eaque.
-#           .row
-#             .col-sm.mt-3
-#               = link_to 'Ver mais', public_position_path(position.slug), class: 'btn btn-danger'
-#               - if user_signed_in?
-#                 - if !UserApplicantQuery.new(current_user.id, position.id).call
                  
-#                   = link_to 'Candidatar-se', public_position_path(position.slug), {:remote => true, "data-target" => "#modal", "data-toggle" => "modal", 'data-backdrop' => 'static', 'data-keyboard' => 'false', class: 'btn btn-success'}
-#             .col-sm.text-right.mt-3.group-social-network
-#               = render partial: 'shared/social_network', locals: {position: position}

app/views/positions/edit.html.haml
%h1 Editar vaga
= render 'form'

app/views/positions/index.html.haml
%h2 Minhas vagas

%table.table
  %thead.thead-dark
    %tr
      %th{:scope => "col"} Título
      %th{:scope => "col"} Carreira
      %th{:scope => "col"} Local
      %th{:scope => "col"} Tipo de contrato
      %th{:scope => "col"} Candidaturas
      %th{:scope => "col"} Ações
  %tbody
    - @positions.each do |position|
      %tr
        %th{:scope => "row"}= position.name
        %td= career_name(position.career)
        %td= modality(position)
        %td= contract_name(position.contract)
        %td= link_to "Ver aplicações (#{position.applicants.count})", position_applicants_path(position), class: 'btn btn-warning btn-sm'
        %td
          = link_to 'Editar', edit_position_path(position), class: 'btn btn-primary btn-sm'
-# %h2 Minhas vagas

-# %table.table
-#   %thead.thead-dark
-#     %tr
-#       %th{:scope => "col"} Título
-#       %th{:scope => "col"} Carreira
-#       %th{:scope => "col"} Local
-#       %th{:scope => "col"} Tipo de contrato
-#       %th{:scope => "col"} Candidaturas
-#       %th{:scope => "col"} Ações
-#   %tbody
-#     - @positions.each do |position|
-#       %tr
-#         %th{:scope => "row"}= position.name
-#         %td= career_name(position.career)
-#         %td= modality(position) # aplicar helper
-#         %td= contract_name(position.contract)
-#         %td
-#           - if position.applicants.size > 0
-#             = link_to "Ver aplicações (#{position.applicants.count})", position_applicants_path(position), class: 'btn btn-warning btn-sm'
-#         %td
-#           = link_to 'Editar', edit_position_path(position), class: 'btn btn-primary btn-sm'

app/views/positions/new.html.haml
%h1 Puplicar vaga
= render 'form'

app/views/positions/public_position.html.haml
%h2= "#{@position.name} - #{@position.company.name}"
%p= "#{career_name(@position.career)} - #{@position.city} / #{modality(@position)}, #{@position.state} - #{contract_name(@position.contract)}"

= @position.description

%br/
%h5 Compartilhar
= render partial: 'shared/social_network', locals: {position: @position}

.wrapper-form-applicant
  - if user_signed_in?
    - if UserApplicantQuery.new(current_user.id, @position.id).call
      %p= "Você já aplicou para essa vaga."
    - else
      %p= "Insira suas informações abaixo para se candidatar à vaga de #{@position.name}"
      = render 'applicants/form'
  - else
    %p Você precisa está logado para se candidatar

app/views/positions/show.html.haml
%h1 Positions#show
%p Find me in app/views/positions/show.html.haml

app/views/shared/_flash_message.html.haml
- if flash.present?
  - if flash[:success].present?
    - @icon = 'success'
    - @tittle = 'Tudo certo!'
    - @message = flash[:success]
  - elsif flash[:error].present?
    - @icon = 'error'
    - @tittle = 'Erro'
    - @message = flash[:error]
  - else
    - @icon = 'success'
    - @tittle = 'Alerta'
    - @message = flash[:notice]

  :javascript
    Swal.fire({
      title: "#{@tittle}",
      text: "#{@message}",
      icon: "#{@icon}",
      confirmButtonText: 'OK!'
    })

app/views/shared/_social_network.html.haml
= link_to image_tag('social-network/linkedin.svg', alt: 'Icone do LinkedIn', height: '32', width: '32'), "https://www.linkedin.com/sharing/share-offsite/?url=#{text_position(position)}"
= link_to image_tag('social-network/whatsapp.svg', alt: 'Icone do Whatsapp', height: '32', width: '32'), "https://wa.me/?text=A empresa #{text_position(position)}"
= link_to image_tag('social-network/twitter.svg', alt: 'Icone do Twitter', height: '32', width: '32'), "https://twitter.com/intent/tweet?text=#{text_position(position)}"
= link_to image_tag('social-network/copy.svg', alt: 'Icone do copiar', height: '32', width: '32', class: 'share-copy-icon'), '#', class: 'copy-url', data: { 'clipboard-text': url_position(position) }

app/views/shared/_topbar.html.haml
%nav.navbar.navbar-expand-md.fixed-top.navbar-dark.bg-dark
  %a.navbar-brand{:href => "#"} Open Vagas
  %button.navbar-toggler.p-0.border-0{"data-toggle" => "offcanvas", :type => "button"}
    %span.navbar-toggler-icon
  #navbarsExampleDefault.navbar-collapse.offcanvas-collapse
    %ul.navbar-nav.mr-auto
      %li.nav-item.active
        %a.nav-link{:href => root_path}
          Inicio
          %span.sr-only (current)
      - unless user_signed_in?
        %li.nav-item
          = link_to 'Login/Cadastro', new_user_session_path, class: 'nav-link'
      - if user_signed_in?
        %li.nav-item.active
          %a.nav-link{:href => dynamic_url_company}
            Minha Empresa
        %li.nav-item.active
          %a.nav-link{:href => positions_url}
            Minhas Vagas
        %li.nav-item
          %a.nav-link.public-position{:href => new_position_path}
            Publicar vaga
        %li.nav-item.dropdown
          %a#dropdown01.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#"} Settings
          .dropdown-menu{"aria-labelledby" => "dropdown01"}
            = link_to('Sair', destroy_user_session_path, method: :delete, class: 'dropdown-item')